#actions/aws-login/action.yml
name: Login to AWS
description: Configure AWS credentials using OIDC

inputs:
    aws-region:
        description: AWS Region
        required: true

runs:
    using: composite

    steps:
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
              role-to-assume: arn:aws:iam::418278132541:role/OIDC-Github
              aws-region: ${{ inputs.aws-region }}
