#.github/workflows/cloudformation-deploy.yml
name: CloudFormation Deploy

on:
    workflow_call:
        inputs:
            aws-region:
                description: AWS Region
                required: true
                type: string

            template-file:
                description: CloudFormation template file path
                required: false
                type: string
                default: "template.yaml"

            s3-bucket:
                description: S3 bucket for packaging
                required: true
                type: string

            cloudformation-deploy:
                description: Deploy Cloudformation stack
                required: true
                type: boolean
                default: false

permissions:
    id-token: write
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Lint Cloudformation Template
              run: |
                  echo "Install cfn-lint"
                  pip install cfn-lint

                  echo "CloudFormation templates:"
                  find . \
                  -type f \
                  \( -name "*.yml" -o -name "*.yaml" \) \
                  -not -path "./.github/*"

                  echo "Linting CloudFormation template recursively..."
                  cfn-lint \
                  $(find . \
                      -type f \
                      \( -name "*.yml" -o -name "*.yaml" \) \
                      -not -path "./.github/*" \
                      -not -name "MainStack.yml")

    pack-template:
        if: ${{ inputs.cloudformation-deploy }}
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Login to AWS
              uses: prabhashbhajnai/ci-template/actions/aws-login@main
              with:
                  aws-region: ${{ inputs.aws-region}}

            - name: Pack Template
              run: |
                  echo "Packing CloudFormation template..."
                  aws cloudformation package \
                        --template-file ${{ inputs.template-file }} \
                        --s3-bucket ${{ inputs.s3-bucket }} \
                        --output-template-file packaged-template.yaml \
                        --region ${{ inputs.aws-region }}

            - name: Validate CloudFormation Template
              run: |
                  echo "Verifying CloudFormation template..."
                  aws cloudformation validate-template \
                          --template-body file://packaged-template.yaml \
                          --region ${{ inputs.aws-region }}

            - name: Upload packaged template
              uses: actions/upload-artifact@main
              with:
                  name: packaged-cloudformation-template
                  path: packaged-template.yaml
                  retention-days: 1

    deploy:
        if: ${{ inputs.cloudformation-deploy }}
        needs: pack-template
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - name: Dowload packaged template
              uses: actions/download-artifact@main
              with:
                  name: packaged-cloudformation-template

            - name: Login to AWS
              uses: prabhashbhajnai/ci-template/actions/aws-login@main
              with:
                  aws-region: ${{ inputs.aws-region}}

            - name: Deploy CloudFormation Stack
              run: |
                  echo "Deploying CloudFormation Stack..."
                  PROJECT_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')

                  PARAMS=""
                  if [ -f "parameters.json" ]; then
                    PARAMS=$(jq -r '.[] | "\(.ParameterKey)=\(.ParameterValue)"' parameters.json)
                  fi

                  echo "Parameters: "
                  echo $PARAMS

                  aws cloudformation deploy \
                      --template-file packaged-template.yaml \
                      --stack-name ${PROJECT_NAME}-stack \
                      --region ${{ inputs.aws-region }} \
                      --parameter-overrides $PARAMS \
                      --capabilities CAPABILITY_NAMED_IAM \
                      --role-arn arn:aws:iam::418278132541:role/CloudFormationExecutionRole \
                      --no-fail-on-empty-changeset 
                  echo "CloudFormation Stack deployed"
