#.github/workflows/cloudformation-deploy.yml
name: CloudFormation Deploy

on:
    workflow_call:
        inputs:
            aws-region:
                description: AWS Region
                required: true
                type: string

            template-file:
                description: CloudFormation template file path
                required: false
                type: string
                default: "template.yaml"

permissions:
    id-token: write
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Login to AWS
              uses: prabhashbhajnai/ci-template/actions/aws-login@main
              with:
                  aws-region: ${{ inputs.aws-region}}

            - name: Verify CloudFormation Template
              run: |
                  echo "Verifying CloudFormation template..."
                  aws cloudformation validate-template \
                        --template-body file://${{ inputs.template-file }} \
                        --region ${{ inputs.aws-region }}

            - name: Deploy CloudFormation Stack
              run: |
                  echo "Deploying CloudFormation Stack..."
                  PROJECT_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')

                  PARAMS=""
                  if [ -f "parameters.json" ]; then
                    PARAMS=$(jq -r '.[] | "\(.ParameterKey)=\(.ParameterValue)"' parameters.json)
                  fi

                  echo "Parameters: "
                  echo $PARAMS

                  aws cloudformation deploy \
                      --template-file ${{ inputs.template-file }} \
                      --stack-name ${PROJECT_NAME}-stack \
                      --region ${{ inputs.aws-region }} \
                      --parameter-overrides $PARAMS \
                      --capabilities CAPABILITY_NAMED_IAM \
                      --role-arn arn:aws:iam::418278132541:role/CloudFormationExecutionRole
                      --no-fail-on-empty-changeset 
                  echo "CloudFormation Stack deployed"
